= Install

To install Vault using this component, there are a few things to decide and prepare.

== Backups

By default, backups using https://k8up.io/k8up/1.0.0/index.html[k8up] are enabled.
For this to work `k8up` needs to be installed on the same cluster using the https://github.com/projectsyn/component-backup-k8up[k8up component].

By default, the component uses the following configuration:

[source,yaml]
----
backup:
  enabled: true
  schedule: '*/13 * * * *'
  keepjobs: 5
  password: '?{vaultkv:${customer:name}/${cluster:name}/vault/${_instance}/backup/password}'
  bucket:
    name: '${_instance}-backup'
    accesskey: '?{vaultkv:${customer:name}/${cluster:name}/vault/${_instance}/backup/s3_access_key}'
    secretkey: '?{vaultkv:${customer:name}/${cluster:name}/vault/${_instance}/backup/s3_secret_key}'
----

The backup configuration expects that there is a bucket with the name `+${INSTANCE}-backup+`.

The three referenced secrets need to be added to the Vault instance associated with the Lieutenant instance managing the cluster on which this component is installed:

* The password to use for backup encryption in key `+clusters/kv/${TENANT_ID}/${CLUSTER_ID}/vault/${INSTANCE}/backup/password}+`
* The access key for the bucket in key `+clusters/kv/${TENANT_ID}/${CLUSTER_ID}/vault/${INSTANCE}/backup/s3_access_key}+`
* The secret key for the bucket in key `+clusters/kv/${TENANT_ID}/${CLUSTER_ID}/vault/${INSTANCE}/backup/s3_secret_key}+`

Unless you explicitly configure multiple instances of the component, a single vault instance will be deployed.
In this case, `+${INSTANCE}+` will simply be `+vault+`.
See <<Multiple Instances>> for more details on how to deploy multiple Vault instances using this component.

== LDAP

By default, only the backup service account and the root user has access to vault.
You have the option to add more authentication methods and policies.
Here is an example to add Vault access to all people in an LDAP group.

[source,yaml]
----
config:
  auth:
    - type: ldap
      description: LDAP auth
      options:
        listing_visibility: "unauth"
      config:
        url: ldaps://ldap.server.net:636
        binddn: "uid=vault-service,ou=Special Users,dc=server,dc=net"
        bindpass: '?{vaultkv:${customer:name}/${cluster:name}/vault/${_instance}/ldappass}'
        userattr: uid
        userdn: "ou=vault,ou=Service Access,ou=Views,dc=server,dc=net"
        groupdn: "ou=Groups,dc=vshn,dc=net"
        groupattr: cn
      groups:
        vault-root:
          policies: cluster-root
  policies:
    - name: cluster-root
      rules: |
        path "clusters/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
        }
----

Under the hood, this component uses `+bank-vaults+` to configure vault.
https://banzaicloud.com/docs/bank-vaults/external-configuration/[This reference] provides more details on how to configure policies and authentication methods.

== Lieutenant Integration

If your Vault should interact with a Lieutenant instance, we need to add some policies and authentication methods.

[source,yaml]
----
config:
  policies:
    - name: syn-cluster
      rules: | # Allow to get cluster's own secrets
        path "clusters/kv/data/+/{{identity.entity.aliases.auth_kubernetes_5b636428.metadata.service_account_name}}/*" {
          capabilities = ["read"]
        }
    - name: lieutenant-operator
      rules: |
        path "clusters/kv/data/*" {
          capabilities = ["read", "create", "update", "delete"]
        }
        path "clusters/kv/metadata/*" {
          capabilities = ["read", "create", "update", "delete", "list"]
        }
        path "clusters/kv/delete/*" {
          capabilities = ["update"]
        }
  auth:
    - type: kubernetes
      roles:
        - name: syn-cluster
          bound_service_account_names: "*"
          bound_service_account_namespaces: lieutenant-prod
          policies: syn-cluster
          ttl: 1h
        - name: lieutenant-operator
          bound_service_account_names: lieutenant-operator
          bound_service_account_namespaces: lieutenant-prod
          policies: lieutenant-operator
          ttl: 1h
----

The `syn-cluster` policy allows each cluster to reveal its own secrets.
The `lieutenant-operator` policy the `+lieutenant-operator+` to read and write secrets.

This setup expects Vault and Lieutenant to be deployed in the same cluster.
If service accounts or namespaces differ in your deployment, you will need to update the snippet above.

[NOTE]
=====
The policy `syn-cluster` allows ArgoCD to read the secrets of its cluster.
The templating entry `+auth_kubernetes_5b636428+` is a name generated by vault on first startup.
This means the policy needs to be added one a second deployment after fetching the name from the deployed Vault.

The entry is the _Accessor_ name of the Kubernetes authentication method.
If can either be fetched from the UI on the _Access_ tab or from the CLI with:

```bash
vault auth list -detailed
```
=====

== Multiple Instances

This component is able to deploy multiple instances of Vault on the same cluster.
You can deploy multiple instances of Vault by instantiating the component.
The following configuration creates two Vault instances named `vault-prod` and `vault-test`.

[source,yaml]
----
applications:
  - vault as vault-prod
  - vault as vault-test
parameters:
  vault_prod:
    config:
      auth:
        - type: ldap
          description: LDAP auth
          options:
            listing_visibility: "unauth"
          config:
            url: ldaps://ldap.server.net:636
            binddn: "uid=vault-service,ou=Special Users,dc=server,dc=net"
            bindpass: '?{vaultkv:${customer:name}/${cluster:name}/vault/${_instance}/ldappass}'
            userattr: uid
            userdn: "ou=vault,ou=Service Access,ou=Views,dc=server,dc=net"
            groupdn: "ou=Groups,dc=vshn,dc=net"
            groupattr: cn
          groups:
            vault-root:
              policies: cluster-root
      policies:
        - name: cluster-root
          rules: |
            path "clusters/*" {
              capabilities = ["create", "read", "update", "delete", "list"]
            }
  vault_test:
    backup:
      enabled: false
----

This will deploy a production vault with LDAP access named `vault-prod` to the namespace `vault-prod`.
And a test vault without backups named `vault-test` to the namespace `vault-test`.

When instantiating a component the `+${INSTANCE}+` parameter is set to the instance's name.
For the production Vault, the parameter is set to `vault-prod` and for the test Vault it's set to `vault-test`.

There are some things to consider when deploying multiple instances of Vault:

* No two instances are allowed to have the same name.
This includes instances of other components.
You should never name an instance the same name as other components.
Naming your Vault instance `argocd` can break in unexpected ways.
In general it's a good idea to prefix your instance with `vault-`.
* You can overwrite both the name and namespace of the instance.
Two instances can either have the same name or be in the same namespace.
If two instances have the same name and namespace bad things will break in unexpected ways.
* If two instances are deployed to the same namespace, they can in principle read each others secrets.
This means in practice you will want to put the production vault in a separate namespace.

More information on how component instantiation works can be found https://syn.tools/commodore/reference/architecture.html#_component_instantiation[here].
