= Parameters

The parent key for all of the following parameters is `vault`.

== `namespace`

[horizontal]
type:: string
default:: `${_instance}`

The namespace in which to deploy this component.

Two intances of vault can be deployed in the same namespace, but the two instances will have access to each others unseal secrets.

== `name`

[horizontal]
type:: string
default:: `${_instance}`

The name of the deployed component.

== `images`

[horizontal]
type:: dictionary

Dictionary containing the container images used by this component.

== `charts`

[horizontal]
type:: dictionary

Dictionary containing the chart versions used by this component.

== `ingress.enabled`

[horizontal]
type:: bool
default:: `true`

Whether to create an ingess object.

== `ingress.host`

[horizontal]
type:: string
default:: `vault.todo.tld`

Defines the FQDN of the ingress, should be overwritten on the cluster level.

== `ingress.annotations`

[horizontal]
type:: dict
default:: {}

The annotations added to the created ingress
Needs to be set according to the deployed ingress controller.


Example:
[source,yaml]
----
annotations:
  cert-manager.io/cluster-issuer: letsencrypt-production
  kubernetes.io/ingress.class: nginx
----

== `storage.size`

[horizontal]
type:: string
default:: `10G`

The requested storage size for secret storage.

== `storage.class`

[horizontal]
type:: string
default:: ``

The kubernetes storage class to request.

== `resources`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
requests:
  memory: 256Mi
  cpu: 250m
limits:
  memory: 512Mi
  cpu: 1000m
----

The resource requests and limits.

== `x_forwarded_for_authorized_addrs`

[horizontal]
type:: string
default:: `127.0.0.1/32`

This parameter allows users to specify the list of source IP CIDRs for which an `X-Forwarded-For` header will be trusted.
Since Vault doesn't accept the empty string as a valid option, we set the parameter to only trust `X-Forwarded-For` headers from `127.0.0.1/32` by default.

If you want to use functionality in Vault which requires the real source IP of requests, you should set this parameter to a CIDR which includes the IPs of your ingress controller.

See also the https://www.vaultproject.io/docs/configuration/listener/tcp#x_forwarded_for_authorized_addrs[Vault documentation].

== `config`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
policies:
  - name: backup
    rules: |
      path "sys/storage/raft/snapshot" {
        capabilities = ["read"]
      }
secrets:
  - type: kv
    path: clusters/kv
    description: General secrets for clusters
    options:
      version: 2
auth:
  - type: kubernetes
    roles:
      - name: backup
        bound_service_account_names: '${vault:name}-backup'
        bound_service_account_namespaces: ${vault:namespace}
        policies: backup
        ttl: 1h
----

The configuration for vault.
The default configuration adds a general key-value secret store and a default backup user.
If this backup user isn't present, backups using k8up won't succeed.
This configuration may directly contain secret references (see example below) as it will be stored in a secret.

Example LDAP configuration:
[source,yaml]
----
auth:
  - type: kubernetes
    roles:
      - name: backup
        bound_service_account_names: vault-backup
        bound_service_account_namespaces: vault
        policies: backup
        ttl: 1h
  - type: ldap
    description: LDAP auth
    options:
      listing_visibility: "unauth"
    config:
      url: ldaps://ldap.todo.com:636
      binddn: "uid=vault-service,ou=Users,dc=todo,dc=com"
      bindpass: ?{vaultkv:${customer:name}/${cluster:name}/vault/ldap/password}
      userattr: uid
      userdn: "ou=vault,ou=Service Access,ou=Views,dc=todo,dc=com"
      groupdn: "ou=Groups,dc=todo,dc=com"
      groupattr: cn
    groups:
      Vault root:
        policies: vault-root
----


== `backup.enabled`

[horizontal]
type:: bool
default:: `true`

Whether to do backups using k8up.

== `backup.schedule`

[horizontal]
type:: string
default:: `*/13 * * * *`

The schedule to perform backups in crontab format.

== `backup.keepjobs`

[horizontal]
type:: string
default:: `5`

== `backup.password`

[horizontal]
type:: string
default:: `?{vaultkv:${customer:name}/${cluster:name}/vault/backup/password}`

The password for the backup.

== `backup.bucket`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
name: '${_instance}-backup'
accesskey: '?{vaultkv:${customer:name}/${cluster:name}/vault/${_instance}/backup/s3_access_key}'
secretkey: '?{vaultkv:${customer:name}/${cluster:name}/vault/${_instance}/backup/s3_secret_key}'
----

The connection information for the S3 bucket to write to.

